# Generated by Django 3.2.16 on 2022-11-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutionId', models.CharField(max_length=100)),
                ('encryptedInstitutionKey', models.CharField(max_length=100)),
                ('institutionKeyIv', models.CharField(max_length=100)),
                ('institutionName', models.CharField(max_length=100)),
                ('passwordKeyNonce', models.CharField(max_length=100)),
                ('verificationKey', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
