# Generated by Django 3.2.16 on 2023-04-10 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institutionId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('encryptedInstitutionKey', models.CharField(max_length=44)),
                ('institutionKeyIv', models.CharField(max_length=24)),
                ('institutionName', models.TextField()),
                ('passwordKeyNonce', models.CharField(max_length=12)),
                ('verificationKey', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('institutionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.institution')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('studentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.student')),
                ('data', models.TextField()),
            ],
        ),
    ]
