// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt7nyY3zly1sfW2mCP9qUYT--tT8f4-MI',
    appId: '1:957533569200:android:9f389e0edf1be6e8',
    messagingSenderId: '957533569200',
    projectId: 'kinga-a6510',
    databaseURL: 'https://kinga-a6510.firebaseio.com',
    storageBucket: 'kinga-a6510.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAILoYM947cIAv8CPpI5idc_7s1MsDJ94',
    appId: '1:957533569200:ios:5566878350b1287bb07b75',
    messagingSenderId: '957533569200',
    projectId: 'kinga-a6510',
    databaseURL: 'https://kinga-a6510.firebaseio.com',
    storageBucket: 'kinga-a6510.appspot.com',
    iosClientId: '957533569200-gnbp4dj9bla7q1aor36aps1vocjerg18.apps.googleusercontent.com',
    iosBundleId: 'com.stoibersoftware.kinga',
  );
}
