# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backend.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbackend.proto\x12\x07\x62\x61\x63kend\x1a\x1bgoogle/protobuf/empty.proto\"+\n\x07Student\x12\x11\n\tstudentId\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xcf\x01\n\x0bInstitution\x12\x15\n\rinstitutionId\x18\x01 \x01(\t\x12\"\n\x08students\x18\x02 \x03(\x0b\x32\x10.backend.Student\x12\x1f\n\x17\x65ncryptedInstitutionKey\x18\x03 \x01(\t\x12\x18\n\x10institutionKeyIv\x18\x04 \x01(\t\x12\x17\n\x0finstitutionName\x18\x05 \x01(\t\x12\x18\n\x10passwordKeyNonce\x18\x06 \x01(\t\x12\x17\n\x0fverificationKey\x18\x07 \x01(\t\"!\n\x0cProfileImage\x12\x11\n\tstudentId\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xfb\x02\n\x07\x42\x61\x63kend\x12\x33\n\rUpdateStudent\x12\x10.backend.Student\x1a\x0e.backend.Empty\"\x00\x12\x37\n\x0fRetrieveStudent\x12\x10.backend.Student\x1a\x10.backend.Student\"\x00\x12;\n\x11UpdateInstitution\x12\x14.backend.Institution\x1a\x0e.backend.Empty\"\x00\x12\x43\n\x13RetrieveInstitution\x12\x14.backend.Institution\x1a\x14.backend.Institution\"\x00\x12=\n\x12UpdateProfileImage\x12\x15.backend.ProfileImage\x1a\x0e.backend.Empty\"\x00\x12\x41\n\x14RetrieveProfileImage\x12\x10.backend.Student\x1a\x15.backend.ProfileImage\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backend_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STUDENT._serialized_start=55
  _STUDENT._serialized_end=98
  _INSTITUTION._serialized_start=101
  _INSTITUTION._serialized_end=308
  _PROFILEIMAGE._serialized_start=310
  _PROFILEIMAGE._serialized_end=343
  _EMPTY._serialized_start=345
  _EMPTY._serialized_end=352
  _BACKEND._serialized_start=355
  _BACKEND._serialized_end=734
# @@protoc_insertion_point(module_scope)
